services:

  backend:

    build: .

    container_name: sign-language-backend

    ports:

      - "8000:8000"


    environment:

      DATABASE_URL:
        postgresql+psycopg://postgres:password@postgres:5432/sign_language_db


    depends_on:

      - postgres



  postgres:

    image:
      postgres:18


    container_name:
      sign-language-postgres


    restart:
      always


    environment:

      POSTGRES_USER:
        postgres


      POSTGRES_PASSWORD:
        password


      POSTGRES_DB:
        sign_language_db


    ports:

      - "5432:5432"


    volumes:

      - postgres_data:/var/lib/postgresql/data



volumes:

  postgres_data: