import { motion } from 'framer-motion';

export default function AISummaryCard({ messageObj, aiConfidence, estimatedSkillLevel }) {
  const [r, g, b] = messageObj?.color || [139, 92, 246];

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-strong rounded-3xl p-6 md:p-8 relative overflow-hidden flex flex-col gap-5 border border-white/10"
      style={{ boxShadow: '0 20px 50px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.08)' }}
    >
      <div
        className="absolute -right-10 -top-10 w-48 h-48 rounded-full pointer-events-none"
        style={{ background: `radial-gradient(circle, rgba(${r},${g},${b},0.2) 0%, transparent 70%)`, filter: 'blur(30px)' }}
      />

      <div className="flex items-center justify-between relative z-10">
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
            style={{ background: `rgba(${r},${g},${b},0.2)`, border: `1px solid rgba(${r},${g},${b},0.4)` }}
          >
            🤖
          </div>
          <div>
            <h3 className="text-lg font-space font-bold text-white">AI Comprehensive Assessment Analysis</h3>
            <p className="text-xs text-white/40">Generated by Sign Language AI Engine v2.0</p>
          </div>
        </div>

        <span
          className="text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider hidden sm:inline-block"
          style={{ background: `rgba(${r},${g},${b},0.15)`, color: `rgb(${r},${g},${b})`, border: `1px solid rgba(${r},${g},${b},0.3)` }}
        >
          {messageObj?.tone || 'Analysis Complete'}
        </span>
      </div>

      <div
        className="p-5 rounded-2xl relative z-10 text-white/90 text-sm leading-relaxed"
        style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}
      >
        <p className="italic text-base font-medium text-white/95">
          &quot;{messageObj?.text}&quot;
        </p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-2 relative z-10 border-t border-white/5">
        <div>
          <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-0.5">AI Confidence</span>
          <span className="text-sm font-space font-bold text-blue-400">{aiConfidence}% High Accuracy</span>
        </div>
        <div>
          <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-0.5">Target Skill Band</span>
          <span className="text-sm font-space font-bold text-purple-400">{estimatedSkillLevel}</span>
        </div>
        <div className="col-span-2 sm:col-span-1">
          <span className="text-[10px] text-white/40 uppercase tracking-widest block mb-0.5">Primary Focus Area</span>
          <span className="text-sm font-space font-bold text-amber-400">Wrist Rotation & Timing</span>
        </div>
      </div>
    </motion.div>
  );
}
